name: pour_nous
description: Clothing Store Co

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_lints: ^2.0.0


  flutter_test:
    sdk: flutter





flutter:

    uses-material-design: true

    assets:
      - assets/logo/logo_pourNous.png
      - assets/images/modelo_um.jpg
      - assets/images/mango_front.jpeg
      - assets/images/mango_back.jpeg
      - assets/images/lichia_front.jpeg
      - assets/images/lichia_back.jpeg
      - assets/images/green_mango_front.jpeg
      - assets/images/green_mango_back.jpeg
      - assets/images/modelo_dois.jpeg
      - assets/images/modelo_tres.jpeg

